services:
  bot:
    build:
      context: ./
      dockerfile: alpine.Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - "./cache:/app/cache"
      - "./logs:/app/logs"
version: "2.4"
